function p2kwiet168597368520983_hbPartsAddedTitle_onClick_seq0(eventobject) {
    summaryService.toggleVisibility(frmSummaryServiceInstallChubb.tabPane.segAddedParts, frmSummaryServiceInstallChubb.tabPane.imgPartsAddedExp);
}